### ISSUE TITLE
Make TemplateRenderer optionable

### ISSUE THREAD

**Issue by Lexinek** [TomasVotruba/nette-single-action-presenter#6]
We are not using Latte (no templates at all) but this error message occurs: `Service '72_IndependentSingleActionPresenter_Template_TemplateRenderer': Service of type Nette\Application\UI\ITemplateFactory needed by IndependentSingleActionPresenter\Template\TemplateRenderer::__construct() not found. Did you register it in configuration file?`

Commenting out `services.neon:2` helped out.

It would be nice to have TemplateRenderer service optionable.

**Comment by TomasVotruba** [comment]
I see. How would you make it optionable?

**Comment by Lexinek** [comment]
I was thinking about some parameter in extension config:
```
extensions:
    independentPresenters: IndependentSingleActionPresenter\DI\IndependentSingleActionPresenterExtension

independentPresenters:
    registerTemplateRenderer: false
```

Default value would be true, also am not sure about naming, it is just idea.
There would be check in extension, whether service is supposed to be registered or not, instead of registering it in `services.neon`.

What do you think about this approach?
